// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BilibiliLogout() {
  return window['go']['main']['App']['BilibiliLogout']();
}

export function CanRestartAsAdmin() {
  return window['go']['main']['App']['CanRestartAsAdmin']();
}

export function CancelDownload(arg1) {
  return window['go']['main']['App']['CancelDownload'](arg1);
}

export function ClearDetectedVideos() {
  return window['go']['main']['App']['ClearDetectedVideos']();
}

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function DownloadBilibiliPart(arg1, arg2, arg3) {
  return window['go']['main']['App']['DownloadBilibiliPart'](arg1, arg2, arg3);
}

export function DownloadBilibiliVideo(arg1, arg2) {
  return window['go']['main']['App']['DownloadBilibiliVideo'](arg1, arg2);
}

export function DownloadDouyinAlbumPartial(arg1, arg2) {
  return window['go']['main']['App']['DownloadDouyinAlbumPartial'](arg1, arg2);
}

export function DownloadDouyinVideo(arg1, arg2) {
  return window['go']['main']['App']['DownloadDouyinVideo'](arg1, arg2);
}

export function DownloadVideo(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['DownloadVideo'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function DownloadVideoWithKey(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['DownloadVideoWithKey'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function DownloadXHSNote(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DownloadXHSNote'](arg1, arg2, arg3, arg4);
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetBilibiliQRCode() {
  return window['go']['main']['App']['GetBilibiliQRCode']();
}

export function GetBilibiliUserInfo() {
  return window['go']['main']['App']['GetBilibiliUserInfo']();
}

export function GetBilibiliVideoInfo(arg1) {
  return window['go']['main']['App']['GetBilibiliVideoInfo'](arg1);
}

export function GetBilibiliVideoInfoWithAllParts(arg1) {
  return window['go']['main']['App']['GetBilibiliVideoInfoWithAllParts'](arg1);
}

export function GetCertPath() {
  return window['go']['main']['App']['GetCertPath']();
}

export function GetCloseAction() {
  return window['go']['main']['App']['GetCloseAction']();
}

export function GetDetectedVideos() {
  return window['go']['main']['App']['GetDetectedVideos']();
}

export function GetDouyinVideoInfo(arg1) {
  return window['go']['main']['App']['GetDouyinVideoInfo'](arg1);
}

export function GetDownloadDir() {
  return window['go']['main']['App']['GetDownloadDir']();
}

export function GetDownloads() {
  return window['go']['main']['App']['GetDownloads']();
}

export function GetLanguage() {
  return window['go']['main']['App']['GetLanguage']();
}

export function GetLogDir() {
  return window['go']['main']['App']['GetLogDir']();
}

export function GetLogSize() {
  return window['go']['main']['App']['GetLogSize']();
}

export function GetProxyDebug() {
  return window['go']['main']['App']['GetProxyDebug']();
}

export function GetProxyPort() {
  return window['go']['main']['App']['GetProxyPort']();
}

export function GetTheme() {
  return window['go']['main']['App']['GetTheme']();
}

export function GetUpstreamProxy() {
  return window['go']['main']['App']['GetUpstreamProxy']();
}

export function GetXHSNoteInfo(arg1) {
  return window['go']['main']['App']['GetXHSNoteInfo'](arg1);
}

export function HasBilibiliSessData() {
  return window['go']['main']['App']['HasBilibiliSessData']();
}

export function InstallCert() {
  return window['go']['main']['App']['InstallCert']();
}

export function IsAdmin() {
  return window['go']['main']['App']['IsAdmin']();
}

export function IsCertInstalled() {
  return window['go']['main']['App']['IsCertInstalled']();
}

export function IsDontAskOnClose() {
  return window['go']['main']['App']['IsDontAskOnClose']();
}

export function IsDontRemindCertWizard() {
  return window['go']['main']['App']['IsDontRemindCertWizard']();
}

export function IsFFmpegAvailable() {
  return window['go']['main']['App']['IsFFmpegAvailable']();
}

export function IsProxyRunning() {
  return window['go']['main']['App']['IsProxyRunning']();
}

export function IsQuitRequested() {
  return window['go']['main']['App']['IsQuitRequested']();
}

export function IsUseUpstreamProxy() {
  return window['go']['main']['App']['IsUseUpstreamProxy']();
}

export function LogFrontend(arg1) {
  return window['go']['main']['App']['LogFrontend'](arg1);
}

export function MinimizeToTray() {
  return window['go']['main']['App']['MinimizeToTray']();
}

export function OpenDownloadDir() {
  return window['go']['main']['App']['OpenDownloadDir']();
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function OpenLogDir() {
  return window['go']['main']['App']['OpenLogDir']();
}

export function PauseDownload(arg1) {
  return window['go']['main']['App']['PauseDownload'](arg1);
}

export function PollBilibiliQRCode(arg1) {
  return window['go']['main']['App']['PollBilibiliQRCode'](arg1);
}

export function RemoveDetectedVideo(arg1) {
  return window['go']['main']['App']['RemoveDetectedVideo'](arg1);
}

export function RemoveDownload(arg1) {
  return window['go']['main']['App']['RemoveDownload'](arg1);
}

export function RequestClose(arg1) {
  return window['go']['main']['App']['RequestClose'](arg1);
}

export function RequestQuit() {
  return window['go']['main']['App']['RequestQuit']();
}

export function RestartAsAdmin() {
  return window['go']['main']['App']['RestartAsAdmin']();
}

export function RestoreFromTray() {
  return window['go']['main']['App']['RestoreFromTray']();
}

export function ResumeDownload(arg1) {
  return window['go']['main']['App']['ResumeDownload'](arg1);
}

export function SelectDownloadDir() {
  return window['go']['main']['App']['SelectDownloadDir']();
}

export function SetBilibiliSessData(arg1) {
  return window['go']['main']['App']['SetBilibiliSessData'](arg1);
}

export function SetCloseAction(arg1) {
  return window['go']['main']['App']['SetCloseAction'](arg1);
}

export function SetDontAskOnClose(arg1) {
  return window['go']['main']['App']['SetDontAskOnClose'](arg1);
}

export function SetDontRemindCertWizard(arg1) {
  return window['go']['main']['App']['SetDontRemindCertWizard'](arg1);
}

export function SetDownloadDir(arg1) {
  return window['go']['main']['App']['SetDownloadDir'](arg1);
}

export function SetFirstRunComplete(arg1) {
  return window['go']['main']['App']['SetFirstRunComplete'](arg1);
}

export function SetLanguage(arg1) {
  return window['go']['main']['App']['SetLanguage'](arg1);
}

export function SetMinimizeToTray(arg1) {
  return window['go']['main']['App']['SetMinimizeToTray'](arg1);
}

export function SetProxyDebug(arg1) {
  return window['go']['main']['App']['SetProxyDebug'](arg1);
}

export function SetShowNotification(arg1) {
  return window['go']['main']['App']['SetShowNotification'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}

export function SetUpstreamProxy(arg1) {
  return window['go']['main']['App']['SetUpstreamProxy'](arg1);
}

export function SetUseUpstreamProxy(arg1) {
  return window['go']['main']['App']['SetUseUpstreamProxy'](arg1);
}

export function StartProxy() {
  return window['go']['main']['App']['StartProxy']();
}

export function StopProxy() {
  return window['go']['main']['App']['StopProxy']();
}

export function UninstallCert() {
  return window['go']['main']['App']['UninstallCert']();
}
