// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {downloader} from '../models';
import {detection} from '../models';
import {xiaohongshu} from '../models';
import {main} from '../models';
import {bilibili} from '../models';
import {douyin} from '../models';
import {settings} from '../models';

export function BilibiliLogout():Promise<void>;

export function CanRestartAsAdmin():Promise<boolean>;

export function CancelDownload(arg1:string,arg2:number,arg3:number):Promise<downloader.StopReceipt>;

export function ClearDetectedVideos():Promise<detection.PublicChange>;

export function ClearLogs():Promise<void>;

export function DownloadBilibiliPart(arg1:string,arg2:number,arg3:number):Promise<string>;

export function DownloadBilibiliVideo(arg1:string,arg2:number):Promise<string>;

export function DownloadDouyinAlbumPartial(arg1:string,arg2:Array<number>):Promise<string>;

export function DownloadDouyinVideo(arg1:string,arg2:string):Promise<string>;

export function DownloadXHSNote(arg1:xiaohongshu.XHSItem,arg2:Array<number>,arg3:string,arg4:string):Promise<void>;

export function GetAppInfo():Promise<main.AppRuntimeInfo>;

export function GetBilibiliQRCode():Promise<bilibili.BilibiliQRCode>;

export function GetBilibiliUserInfo():Promise<bilibili.BilibiliUserInfo>;

export function GetBilibiliVideoInfo(arg1:string):Promise<bilibili.BilibiliVideo>;

export function GetBilibiliVideoInfoWithAllParts(arg1:string):Promise<bilibili.BilibiliVideo>;

export function GetCertPath():Promise<string>;

export function GetDetectedVideos():Promise<detection.PublicSnapshot>;

export function GetDouyinVideoInfo(arg1:string):Promise<douyin.DouyinItem>;

export function GetDownloads():Promise<Array<downloader.PublicDownloadTask>>;

export function GetLogDir():Promise<string>;

export function GetLogSize():Promise<number>;

export function GetSettings():Promise<settings.SettingsSnapshot>;

export function GetXHSNoteInfo(arg1:string):Promise<xiaohongshu.XHSItem>;

export function HasBilibiliSessData():Promise<boolean>;

export function InstallCert():Promise<void>;

export function InstallFFmpeg():Promise<string>;

export function IsAdmin():Promise<boolean>;

export function IsCertInstalled():Promise<boolean>;

export function IsFFmpegAvailable():Promise<boolean>;

export function IsProxyRunning():Promise<boolean>;

export function IsQuitRequested():Promise<boolean>;

export function LogFrontend(arg1:string):Promise<void>;

export function MinimizeToTray():Promise<void>;

export function OpenDownloadDir():Promise<void>;

export function OpenFile(arg1:string):Promise<void>;

export function OpenLogDir():Promise<void>;

export function PauseDownload(arg1:string,arg2:number,arg3:number):Promise<downloader.StopReceipt>;

export function PollBilibiliQRCode(arg1:string):Promise<bilibili.BilibiliLoginStatus>;

export function RemoveDetectedVideo(arg1:string):Promise<detection.PublicChange>;

export function RemoveDownload(arg1:string,arg2:number,arg3:number):Promise<downloader.StopReceipt>;

export function RequestClose(arg1:string):Promise<void>;

export function RequestQuit():Promise<void>;

export function RestartAsAdmin():Promise<void>;

export function RestoreFromTray():Promise<void>;

export function ResumeDownload(arg1:string,arg2:number,arg3:number):Promise<void>;

export function RetryDownload(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SelectDownloadDir():Promise<string>;

export function SetBilibiliSessData(arg1:string):Promise<void>;

export function StartDetectedDownload(arg1:string,arg2:string):Promise<downloader.PublicDownloadTask>;

export function StartProxy():Promise<void>;

export function StopProxy():Promise<void>;

export function TakeLegacyDownloadNotice():Promise<downloader.LegacyTaskStateNotice>;

export function UninstallCert():Promise<void>;

export function UpdateSettings(arg1:settings.SettingsPatch):Promise<settings.SettingsUpdateResult>;
