// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {downloader} from '../models';
import {api} from '../models';
import {douyin} from '../models';

export function CancelDownload(arg1:string):Promise<void>;

export function ClearDetectedVideos():Promise<void>;

export function DownloadBilibiliPart(arg1:string,arg2:number,arg3:number):Promise<string>;

export function DownloadBilibiliVideo(arg1:string,arg2:number):Promise<string>;

export function DownloadDouyinVideo(arg1:string,arg2:string):Promise<string>;

export function DownloadVideo(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<Record<string, any>>;

export function DownloadVideoWithKey(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string):Promise<Record<string, any>>;

export function GetAppInfo():Promise<Record<string, any>>;

export function GetBilibiliSessData():Promise<string>;

export function GetBilibiliVideoInfo(arg1:string):Promise<downloader.BilibiliVideo>;

export function GetCertPath():Promise<string>;

export function GetDetectedVideos():Promise<Array<api.DetectedVideo>>;

export function GetDouyinVideoInfo(arg1:string):Promise<douyin.DouyinItem>;

export function GetDownloadDir():Promise<string>;

export function GetDownloads():Promise<Array<Record<string, any>>>;

export function GetLanguage():Promise<string>;

export function GetLogDir():Promise<string>;

export function GetProxyDebug():Promise<boolean>;

export function GetProxyPort():Promise<number>;

export function GetTheme():Promise<string>;

export function GetUpstreamProxy():Promise<string>;

export function InstallCert():Promise<void>;

export function IsCertInstalled():Promise<boolean>;

export function IsFFmpegAvailable():Promise<boolean>;

export function IsFirstRunComplete():Promise<boolean>;

export function IsMinimizeToTrayEnabled():Promise<boolean>;

export function IsProxyRunning():Promise<boolean>;

export function IsShowNotificationEnabled():Promise<boolean>;

export function IsUseUpstreamProxy():Promise<boolean>;

export function MinimizeToTray():Promise<void>;

export function OpenDownloadDir():Promise<void>;

export function OpenFile(arg1:string):Promise<void>;

export function OpenLogDir():Promise<void>;

export function PauseDownload(arg1:string):Promise<void>;

export function RemoveDetectedVideo(arg1:string):Promise<void>;

export function RemoveDownload(arg1:string):Promise<void>;

export function RestoreFromTray():Promise<void>;

export function ResumeDownload(arg1:string):Promise<void>;

export function SelectDownloadDir():Promise<string>;

export function SetBilibiliSessData(arg1:string):Promise<void>;

export function SetDownloadDir(arg1:string):Promise<void>;

export function SetFirstRunComplete(arg1:boolean):Promise<void>;

export function SetLanguage(arg1:string):Promise<void>;

export function SetMinimizeToTray(arg1:boolean):Promise<void>;

export function SetProxyDebug(arg1:boolean):Promise<void>;

export function SetShowNotification(arg1:boolean):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;

export function SetUpstreamProxy(arg1:string):Promise<void>;

export function SetUseUpstreamProxy(arg1:boolean):Promise<void>;

export function ShowNotification(arg1:string,arg2:string):Promise<void>;

export function StartProxy():Promise<void>;

export function StopProxy():Promise<void>;

export function UninstallCert():Promise<void>;
