// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelDownload(arg1) {
  return window['go']['main']['App']['CancelDownload'](arg1);
}

export function ClearDetectedVideos() {
  return window['go']['main']['App']['ClearDetectedVideos']();
}

export function DownloadBilibiliPart(arg1, arg2, arg3) {
  return window['go']['main']['App']['DownloadBilibiliPart'](arg1, arg2, arg3);
}

export function DownloadBilibiliVideo(arg1, arg2) {
  return window['go']['main']['App']['DownloadBilibiliVideo'](arg1, arg2);
}

export function DownloadVideo(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['DownloadVideo'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetBilibiliSessData() {
  return window['go']['main']['App']['GetBilibiliSessData']();
}

export function GetBilibiliVideoInfo(arg1) {
  return window['go']['main']['App']['GetBilibiliVideoInfo'](arg1);
}

export function GetCertPath() {
  return window['go']['main']['App']['GetCertPath']();
}

export function GetDetectedVideos() {
  return window['go']['main']['App']['GetDetectedVideos']();
}

export function GetDownloadDir() {
  return window['go']['main']['App']['GetDownloadDir']();
}

export function GetDownloads() {
  return window['go']['main']['App']['GetDownloads']();
}

export function GetLanguage() {
  return window['go']['main']['App']['GetLanguage']();
}

export function GetLogDir() {
  return window['go']['main']['App']['GetLogDir']();
}

export function GetProxyPort() {
  return window['go']['main']['App']['GetProxyPort']();
}

export function GetTheme() {
  return window['go']['main']['App']['GetTheme']();
}

export function GetUpstreamProxy() {
  return window['go']['main']['App']['GetUpstreamProxy']();
}

export function InstallCert() {
  return window['go']['main']['App']['InstallCert']();
}

export function IsCertInstalled() {
  return window['go']['main']['App']['IsCertInstalled']();
}

export function IsFFmpegAvailable() {
  return window['go']['main']['App']['IsFFmpegAvailable']();
}

export function IsFirstRunComplete() {
  return window['go']['main']['App']['IsFirstRunComplete']();
}

export function IsMinimizeToTrayEnabled() {
  return window['go']['main']['App']['IsMinimizeToTrayEnabled']();
}

export function IsProxyRunning() {
  return window['go']['main']['App']['IsProxyRunning']();
}

export function IsShowNotificationEnabled() {
  return window['go']['main']['App']['IsShowNotificationEnabled']();
}

export function IsUseUpstreamProxy() {
  return window['go']['main']['App']['IsUseUpstreamProxy']();
}

export function MinimizeToTray() {
  return window['go']['main']['App']['MinimizeToTray']();
}

export function OpenDownloadDir() {
  return window['go']['main']['App']['OpenDownloadDir']();
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function OpenLogDir() {
  return window['go']['main']['App']['OpenLogDir']();
}

export function PauseDownload(arg1) {
  return window['go']['main']['App']['PauseDownload'](arg1);
}

export function RemoveDetectedVideo(arg1) {
  return window['go']['main']['App']['RemoveDetectedVideo'](arg1);
}

export function RemoveDownload(arg1) {
  return window['go']['main']['App']['RemoveDownload'](arg1);
}

export function RestoreFromTray() {
  return window['go']['main']['App']['RestoreFromTray']();
}

export function ResumeDownload(arg1) {
  return window['go']['main']['App']['ResumeDownload'](arg1);
}

export function SelectDownloadDir() {
  return window['go']['main']['App']['SelectDownloadDir']();
}

export function SetBilibiliSessData(arg1) {
  return window['go']['main']['App']['SetBilibiliSessData'](arg1);
}

export function SetDownloadDir(arg1) {
  return window['go']['main']['App']['SetDownloadDir'](arg1);
}

export function SetFirstRunComplete(arg1) {
  return window['go']['main']['App']['SetFirstRunComplete'](arg1);
}

export function SetLanguage(arg1) {
  return window['go']['main']['App']['SetLanguage'](arg1);
}

export function SetMinimizeToTray(arg1) {
  return window['go']['main']['App']['SetMinimizeToTray'](arg1);
}

export function SetShowNotification(arg1) {
  return window['go']['main']['App']['SetShowNotification'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}

export function SetUpstreamProxy(arg1) {
  return window['go']['main']['App']['SetUpstreamProxy'](arg1);
}

export function SetUseUpstreamProxy(arg1) {
  return window['go']['main']['App']['SetUseUpstreamProxy'](arg1);
}

export function ShowNotification(arg1, arg2) {
  return window['go']['main']['App']['ShowNotification'](arg1, arg2);
}

export function StartProxy() {
  return window['go']['main']['App']['StartProxy']();
}

export function StopProxy() {
  return window['go']['main']['App']['StopProxy']();
}

export function UninstallCert() {
  return window['go']['main']['App']['UninstallCert']();
}
